// Default game content, inserted into the CMS database on first run
// (and restorable from the admin dashboard).
import {
  rankedSchema,
  type AssetDef,
  type BotDef,
  type ContentBundle,
  type Faction,
  type MapDef,
  type ParticleDef,
  type ProjectileDef,
  type Settings,
  type UnitDef,
  type WeaponDef,
} from './schema';

const factions: Faction[] = [
  { id: 'bo-lac', name: 'Bộ lạc', color: '#c8692f', icon: 'mountain', order: 1 },
  { id: 'trung-co', name: 'Trung cổ', color: '#3f7fd6', icon: 'shield', order: 2 },
  { id: 'phuong-dong', name: 'Phương Đông', color: '#d23c3c', icon: 'lamp', order: 3 },
  { id: 'huyen-thoai', name: 'Huyền thoại', color: '#8e44ad', icon: 'flame', order: 4 },
  { id: 'thanh-tri', name: 'Thành trì', color: '#7d776e', icon: 'castle', order: 5 },
];

const P = (p: Partial<ParticleDef> & Pick<ParticleDef, 'id' | 'name'>): ParticleDef => ({
  shape: 'cube',
  additive: false,
  count: 10,
  rate: 30,
  lifetime: [0.4, 0.8],
  speed: [1, 3],
  direction: 'hemisphere',
  spread: 0.5,
  gravity: 9.8,
  drag: 0.5,
  size: [0.2, 0.02],
  colorStart: '#ffffff',
  colorEnd: '#999999',
  spin: 3,
  emitRadius: 0.1,
  ...p,
});

const particles: ParticleDef[] = [
  P({ id: 'spark', name: 'Tia lửa va chạm', shape: 'tetra', additive: true, count: 8, lifetime: [0.2, 0.45], speed: [3, 7], direction: 'forward', spread: 0.7, gravity: 12, drag: 1, size: [0.13, 0], colorStart: '#fff3b0', colorEnd: '#ff8a1f', spin: 12 }),
  P({ id: 'hit-dust', name: 'Bụi va chạm', shape: 'cube', count: 10, lifetime: [0.4, 0.8], speed: [1.5, 4], direction: 'hemisphere', gravity: 6, drag: 2, size: [0.22, 0.04], colorStart: '#d9c7a5', colorEnd: '#8a7a60' }),
  P({ id: 'hit-chunk', name: 'Mảnh đỏ', shape: 'cube', count: 8, lifetime: [0.4, 0.9], speed: [2, 5], direction: 'forward', spread: 0.8, gravity: 14, drag: 0.6, size: [0.14, 0.03], colorStart: '#d8323a', colorEnd: '#7a1010', spin: 8 }),
  P({ id: 'fire', name: 'Lửa phun', shape: 'sphere', additive: true, count: 16, rate: 60, lifetime: [0.35, 0.8], speed: [5, 11], direction: 'forward', spread: 0.22, gravity: -3, drag: 1.5, size: [0.35, 1.0], colorStart: '#ffd24a', colorEnd: '#000000', spin: 2 }),
  P({ id: 'fire-trail', name: 'Vệt lửa', shape: 'sphere', additive: true, count: 2, rate: 45, lifetime: [0.2, 0.45], speed: [0.2, 0.8], direction: 'sphere', gravity: -2, drag: 1, size: [0.25, 0.05], colorStart: '#ffb13d', colorEnd: '#000000' }),
  P({ id: 'explosion', name: 'Nổ', shape: 'sphere', additive: true, count: 36, lifetime: [0.3, 0.9], speed: [3, 10], direction: 'sphere', gravity: -2, drag: 3, size: [0.7, 1.5], colorStart: '#ffe07a', colorEnd: '#000000', spin: 2, emitRadius: 0.5 }),
  P({ id: 'smoke', name: 'Khói', shape: 'sphere', count: 14, lifetime: [0.8, 1.8], speed: [0.5, 2.5], direction: 'up', spread: 0.6, gravity: -1.5, drag: 1.5, size: [0.9, 0.1], colorStart: '#8f8f8f', colorEnd: '#dadada', spin: 1, emitRadius: 0.6 }),
  P({ id: 'heal', name: 'Hồi máu', shape: 'tetra', additive: true, count: 12, lifetime: [0.6, 1.2], speed: [1, 2.5], direction: 'up', spread: 0.6, gravity: -2, drag: 1, size: [0.18, 0], colorStart: '#b6ff9e', colorEnd: '#1a5a12', spin: 6, emitRadius: 0.4 }),
  P({ id: 'magic', name: 'Phép thuật', shape: 'sphere', additive: true, count: 14, lifetime: [0.3, 0.7], speed: [1, 3], direction: 'sphere', gravity: -1, drag: 2, size: [0.25, 0], colorStart: '#e0a3ff', colorEnd: '#2a0a4a', emitRadius: 0.3 }),
  P({ id: 'death-poof', name: 'Khói tử trận', shape: 'cube', count: 12, lifetime: [0.5, 1.0], speed: [1, 3], direction: 'hemisphere', gravity: -0.5, drag: 2, size: [0.32, 0.02], colorStart: '#ffffff', colorEnd: '#bdbdbd', spin: 4, emitRadius: 0.4 }),
  P({ id: 'splash', name: 'Nước bắn', shape: 'tetra', count: 16, lifetime: [0.4, 0.9], speed: [3, 6], direction: 'up', spread: 0.5, gravity: 14, drag: 0.4, size: [0.18, 0.04], colorStart: '#d8f1ff', colorEnd: '#3a8fd0', spin: 6, emitRadius: 0.4 }),
  P({ id: 'land-dust', name: 'Bụi tiếp đất', shape: 'cube', count: 8, lifetime: [0.4, 0.8], speed: [1, 3], direction: 'hemisphere', gravity: 3, drag: 2.5, size: [0.25, 0.03], colorStart: '#c8b28a', colorEnd: '#7a6a50', emitRadius: 0.3 }),
  P({ id: 'debris', name: 'Đá văng', shape: 'tetra', count: 22, lifetime: [0.6, 1.2], speed: [3, 8], direction: 'hemisphere', gravity: 16, drag: 0.4, size: [0.3, 0.08], colorStart: '#9a8f80', colorEnd: '#5a5048', spin: 10, emitRadius: 0.6 }),
  P({ id: 'muzzle-flash', name: 'Chớp nòng súng', shape: 'tetra', additive: true, count: 16, lifetime: [0.05, 0.16], speed: [4, 12], direction: 'forward', spread: 0.25, gravity: 0, drag: 5, size: [0.42, 0.04], colorStart: '#fff6c8', colorEnd: '#ff6a10', spin: 20 }),
  P({ id: 'gun-smoke', name: 'Khói súng', shape: 'sphere', count: 10, lifetime: [0.8, 1.6], speed: [0.6, 2.2], direction: 'forward', spread: 0.6, gravity: -0.8, drag: 2.2, size: [0.36, 0.08], colorStart: '#ebe7df', colorEnd: '#bdb8b0', spin: 1, emitRadius: 0.1 }),
  P({ id: 'lightning-spark', name: 'Tia điện', shape: 'tetra', additive: true, count: 18, lifetime: [0.15, 0.4], speed: [4, 11], direction: 'sphere', gravity: 6, drag: 2, size: [0.15, 0], colorStart: '#ffffff', colorEnd: '#2a5aff', spin: 15, emitRadius: 0.4 }),
  P({ id: 'shock-dust', name: 'Bụi sóng xung kích', shape: 'cube', count: 28, lifetime: [0.5, 1.1], speed: [4, 10], direction: 'hemisphere', gravity: 10, drag: 2.2, size: [0.36, 0.05], colorStart: '#cbb894', colorEnd: '#7a6a50', spin: 6, emitRadius: 1.2 }),
  P({ id: 'burn', name: 'Lửa cháy trên người', shape: 'sphere', additive: true, count: 3, rate: 22, lifetime: [0.25, 0.55], speed: [0.6, 1.8], direction: 'up', spread: 0.5, gravity: -4, drag: 1, size: [0.3, 0.02], colorStart: '#ffcf4a', colorEnd: '#000000', spin: 2, emitRadius: 0.25 }),
  P({ id: 'ember', name: 'Tàn lửa', shape: 'tetra', additive: true, count: 26, lifetime: [0.5, 1.3], speed: [2, 7], direction: 'hemisphere', gravity: -1, drag: 1.5, size: [0.12, 0], colorStart: '#ffd27a', colorEnd: '#2a0800', spin: 10, emitRadius: 1.2 }),
  P({ id: 'whirl-dust', name: 'Bụi lốc xoáy', shape: 'cube', count: 6, rate: 40, lifetime: [0.5, 1.0], speed: [2, 5], direction: 'up', spread: 0.9, gravity: -2, drag: 1.5, size: [0.32, 0.05], colorStart: '#c9b894', colorEnd: '#8a7a60', spin: 8, emitRadius: 1.4 }),
  P({ id: 'flame-jet', name: 'Luồng lửa phun xa', shape: 'sphere', additive: true, count: 14, rate: 60, lifetime: [0.3, 0.6], speed: [10, 17], direction: 'forward', spread: 0.16, gravity: -4, drag: 1.3, size: [0.22, 0.85], colorStart: '#ff9a2a', colorEnd: '#1a0200', spin: 3 }),
  P({ id: 'heal-burst', name: 'Hồi máu diện rộng', shape: 'tetra', additive: true, count: 32, lifetime: [0.6, 1.3], speed: [1.5, 4.5], direction: 'up', spread: 0.9, gravity: -3, drag: 1.2, size: [0.22, 0], colorStart: '#d8ffb0', colorEnd: '#0a3a0a', spin: 6, emitRadius: 1.8 }),
];

const Proj = (p: Partial<ProjectileDef> & Pick<ProjectileDef, 'id' | 'name' | 'model'>): ProjectileDef => ({
  scale: 1,
  color: '#ffffff',
  gravity: 9.8,
  hitRadius: 0.3,
  lifetime: 8,
  trailParticleId: null,
  impactParticleId: null,
  stick: false,
  ...p,
});

const projectiles: ProjectileDef[] = [
  Proj({ id: 'arrow', name: 'Mũi tên', model: 'arrow', hitRadius: 0.25, stick: true, impactParticleId: 'hit-dust' }),
  Proj({ id: 'fire-arrow', name: 'Hỏa tiễn', model: 'arrow', color: '#ff8a1f', hitRadius: 0.25, stick: true, trailParticleId: 'fire-trail', impactParticleId: 'explosion' }),
  Proj({ id: 'spear', name: 'Lao', model: 'spear', hitRadius: 0.3, stick: true, impactParticleId: 'hit-dust' }),
  Proj({ id: 'stone', name: 'Hòn đá', model: 'stone', scale: 1, impactParticleId: 'hit-dust' }),
  Proj({ id: 'boulder', name: 'Tảng đá', model: 'boulder', scale: 1, hitRadius: 0.8, impactParticleId: 'debris', lifetime: 12 }),
  Proj({ id: 'fireball', name: 'Cầu lửa', model: 'fireball', color: '#ff7a1a', gravity: 2, hitRadius: 0.5, trailParticleId: 'fire-trail', impactParticleId: 'explosion' }),
  Proj({ id: 'bullet', name: 'Đạn chì', model: 'bullet', color: '#ffe7a0', gravity: 1.5, hitRadius: 0.18, lifetime: 2, impactParticleId: 'spark' }),
  Proj({ id: 'fire-pot', name: 'Hũ dầu lửa', model: 'boulder', scale: 0.9, color: '#ff7a1a', hitRadius: 0.8, lifetime: 12, trailParticleId: 'fire-trail', impactParticleId: 'explosion' }),
  Proj({ id: 'shuriken', name: 'Phi tiêu', model: 'shuriken', gravity: 2, hitRadius: 0.25, lifetime: 3, stick: true, impactParticleId: 'spark' }),
  Proj({ id: 'meteor', name: 'Thiên thạch', model: 'meteor', scale: 1.6, color: '#ff6a1a', gravity: 0, hitRadius: 1, trailParticleId: 'fire-trail', impactParticleId: 'explosion' }),
];

const W = (w: Partial<WeaponDef> & Pick<WeaponDef, 'id' | 'name' | 'attack' | 'damage' | 'damageType' | 'range' | 'cooldown' | 'windup'>): WeaponDef => ({
  minRange: 0,
  knockback: 0,
  knockUp: 0,
  cleaveArc: 0,
  maxTargets: 1,
  splashRadius: 0,
  projectileId: null,
  projectileSpeed: 20,
  spread: 0,
  volley: 1,
  hitParticleId: null,
  fireParticleId: null,
  castStyle: 'auto',
  initialCooldown: 0,
  minTargets: 1,
  duration: 0,
  interval: 0.2,
  stunDuration: 0,
  burnDps: 0,
  burnDuration: 0,
  chainCount: 4,
  chainRange: 6,
  chainFalloff: 0.8,
  strikeVfx: 'lightning',
  strikeCount: 1,
  strikeDelay: 0.5,
  strikeInterval: 0.15,
  strikeSpread: 0,
  zoneSpeed: 3,
  pull: 8,
  lift: 8,
  vfxColor: '#9fd8ff',
  areaParticleId: null,
  ...w,
});

const weapons: WeaponDef[] = [
  W({ id: 'club', name: 'Gậy gỗ', attack: 'melee', damage: 20, damageType: 'blunt', range: 1.1, cooldown: 1.1, windup: 0.35, knockback: 3, hitParticleId: 'hit-dust' }),
  W({ id: 'small-club', name: 'Gậy ngắn', attack: 'melee', damage: 12, damageType: 'blunt', range: 1.0, cooldown: 1.2, windup: 0.3, knockback: 2, hitParticleId: 'hit-dust' }),
  W({ id: 'throw-spear', name: 'Ném lao', attack: 'projectile', damage: 45, damageType: 'pierce', range: 22, cooldown: 3, windup: 0.5, knockback: 3, projectileId: 'spear', projectileSpeed: 18, spread: 0.8, hitParticleId: 'hit-chunk' }),
  W({ id: 'throw-stone', name: 'Ném đá', attack: 'projectile', damage: 22, damageType: 'blunt', range: 16, cooldown: 1.8, windup: 0.4, knockback: 3, projectileId: 'stone', projectileSpeed: 14, spread: 1, hitParticleId: 'hit-dust' }),
  W({ id: 'chief-axe', name: 'Rìu tù trưởng', attack: 'melee', damage: 70, damageType: 'slash', range: 1.6, cooldown: 1.4, windup: 0.45, knockback: 9, knockUp: 4, cleaveArc: 100, maxTargets: 4, hitParticleId: 'spark' }),
  W({ id: 'mammoth-tusks', name: 'Ngà voi ma mút', attack: 'melee', damage: 90, damageType: 'blunt', range: 2.2, cooldown: 1.8, windup: 0.6, knockback: 22, knockUp: 8, cleaveArc: 120, maxTargets: 6, hitParticleId: 'hit-dust' }),
  W({ id: 'sword', name: 'Kiếm', attack: 'melee', damage: 22, damageType: 'slash', range: 1.2, cooldown: 1.0, windup: 0.3, knockback: 3, hitParticleId: 'spark' }),
  W({ id: 'bow', name: 'Cung', attack: 'projectile', damage: 26, damageType: 'pierce', range: 30, cooldown: 2, windup: 0.7, knockback: 1, projectileId: 'arrow', projectileSpeed: 26, spread: 1, hitParticleId: 'hit-chunk' }),
  W({ id: 'heal-staff', name: 'Gậy hồi phục', attack: 'heal', damage: 18, damageType: 'magic', range: 8, cooldown: 1.2, windup: 0.4, hitParticleId: 'heal' }),
  W({ id: 'knight-sword', name: 'Kiếm hiệp sĩ', attack: 'melee', damage: 60, damageType: 'slash', range: 1.4, cooldown: 1.2, windup: 0.4, knockback: 6, cleaveArc: 60, maxTargets: 2, hitParticleId: 'spark' }),
  W({ id: 'lance', name: 'Thương kỵ binh', attack: 'melee', damage: 80, damageType: 'pierce', range: 2, cooldown: 1.6, windup: 0.15, knockback: 14, knockUp: 3, hitParticleId: 'spark' }),
  W({ id: 'catapult', name: 'Máy bắn đá', attack: 'projectile', damage: 150, damageType: 'blunt', range: 70, minRange: 14, cooldown: 6, windup: 1, knockback: 18, knockUp: 9, splashRadius: 4, projectileId: 'boulder', projectileSpeed: 20, spread: 1.2, hitParticleId: 'hit-dust' }),
  W({ id: 'greatsword', name: 'Đại kiếm', attack: 'melee', damage: 130, damageType: 'slash', range: 2.2, cooldown: 1.5, windup: 0.55, knockback: 14, knockUp: 5, cleaveArc: 140, maxTargets: 6, hitParticleId: 'spark' }),
  W({ id: 'hoplite-spear', name: 'Giáo dài', attack: 'melee', damage: 30, damageType: 'pierce', range: 2.4, cooldown: 1.1, windup: 0.3, knockback: 4, hitParticleId: 'hit-chunk' }),
  W({ id: 'monk-staff', name: 'Côn võ tăng', attack: 'melee', damage: 25, damageType: 'blunt', range: 1.4, cooldown: 0.6, windup: 0.15, knockback: 7, knockUp: 2, hitParticleId: 'hit-dust' }),
  W({ id: 'elephant-bow', name: 'Cung trên voi', attack: 'projectile', damage: 30, damageType: 'pierce', range: 28, cooldown: 1.2, windup: 0.4, knockback: 1, projectileId: 'arrow', projectileSpeed: 26, spread: 1.2, hitParticleId: 'hit-chunk' }),
  W({ id: 'fire-bow', name: 'Cung hỏa tiễn', attack: 'projectile', damage: 22, damageType: 'fire', range: 32, cooldown: 2.4, windup: 0.8, knockback: 4, knockUp: 2, splashRadius: 2.5, projectileId: 'fire-arrow', projectileSpeed: 24, spread: 1.4 }),
  W({ id: 'talons', name: 'Móng vuốt', attack: 'melee', damage: 25, damageType: 'slash', range: 1.2, cooldown: 0.9, windup: 0.2, knockback: 4, hitParticleId: 'hit-chunk' }),
  W({ id: 'raptor-bite', name: 'Cắn xé', attack: 'melee', damage: 34, damageType: 'slash', range: 1.6, cooldown: 0.85, windup: 0.25, knockback: 5, knockUp: 1, cleaveArc: 70, maxTargets: 2, hitParticleId: 'hit-chunk' }),
  W({ id: 'rex-bite', name: 'Ngoạm bạo chúa', attack: 'melee', damage: 180, damageType: 'slash', range: 3, cooldown: 1.9, windup: 0.6, knockback: 26, knockUp: 9, cleaveArc: 120, maxTargets: 5, hitParticleId: 'hit-chunk' }),
  W({ id: 'stego-tail', name: 'Quật đuôi gai', attack: 'melee', damage: 110, damageType: 'pierce', range: 2.8, cooldown: 1.7, windup: 0.55, knockback: 20, knockUp: 6, cleaveArc: 180, maxTargets: 6, hitParticleId: 'hit-chunk' }),
  W({ id: 'para-tail', name: 'Quất đuôi', attack: 'melee', damage: 55, damageType: 'blunt', range: 2, cooldown: 1, windup: 0.3, knockback: 10, knockUp: 2, cleaveArc: 90, maxTargets: 3, hitParticleId: 'hit-dust' }),
  W({ id: 'tri-horns', name: 'Húc sừng', attack: 'melee', damage: 95, damageType: 'pierce', range: 2.4, cooldown: 1.5, windup: 0.4, knockback: 18, knockUp: 5, cleaveArc: 100, maxTargets: 4, hitParticleId: 'hit-chunk' }),
  W({ id: 'fireball-staff', name: 'Trượng cầu lửa', attack: 'projectile', damage: 80, damageType: 'fire', range: 30, cooldown: 3.5, windup: 0.9, knockback: 10, knockUp: 5, splashRadius: 4, projectileId: 'fireball', projectileSpeed: 16, spread: 0.6, fireParticleId: 'magic' }),
  W({ id: 'giant-club', name: 'Chùy khổng lồ', attack: 'melee', damage: 135, damageType: 'blunt', range: 2.8, cooldown: 2, windup: 0.7, knockback: 28, knockUp: 10, cleaveArc: 120, maxTargets: 5, hitParticleId: 'hit-dust' }),
  W({ id: 'dragon-breath', name: 'Hơi thở rồng', attack: 'breath', damage: 14, damageType: 'fire', range: 13, cooldown: 0.2, windup: 0, knockback: 1, cleaveArc: 40, maxTargets: 12, fireParticleId: 'fire' }),
  W({ id: 'baby-dragon-breath', name: 'Hơi thở rồng con', attack: 'breath', damage: 7, damageType: 'fire', range: 8, cooldown: 0.25, windup: 0, knockback: 1, cleaveArc: 35, maxTargets: 6, fireParticleId: 'fire' }),
  W({ id: 'musket', name: 'Súng hỏa mai', attack: 'projectile', damage: 60, damageType: 'pierce', range: 34, cooldown: 3.4, windup: 0.55, knockback: 6, knockUp: 1.5, projectileId: 'bullet', projectileSpeed: 110, spread: 0.5, hitParticleId: 'hit-chunk', fireParticleId: 'muzzle-flash', areaParticleId: 'gun-smoke', castStyle: 'gun' }),
  W({ id: 'zap', name: 'Tia sét', attack: 'chain', damage: 28, damageType: 'magic', range: 14, cooldown: 1.6, windup: 0.35, knockback: 2, chainCount: 2, chainRange: 5, chainFalloff: 0.7, stunDuration: 0.25, hitParticleId: 'lightning-spark', vfxColor: '#8fd3ff', castStyle: 'palm' }),
  W({ id: 'katana', name: 'Kiếm katana', attack: 'melee', damage: 45, damageType: 'slash', range: 1.3, cooldown: 0.75, windup: 0.2, knockback: 3, hitParticleId: 'spark' }),
  W({ id: 'fire-catapult', name: 'Máy bắn đá lửa', attack: 'projectile', damage: 120, damageType: 'fire', range: 72, minRange: 14, cooldown: 7, windup: 1, knockback: 14, knockUp: 7, splashRadius: 5, projectileId: 'fire-pot', projectileSpeed: 20, spread: 1.4, burnDps: 20, burnDuration: 4, hitParticleId: 'ember' }),
  W({ id: 'phi-tieu', name: 'Ném phi tiêu', attack: 'projectile', damage: 30, damageType: 'pierce', range: 18, cooldown: 5, windup: 0.3, knockback: 1, projectileId: 'shuriken', projectileSpeed: 30, spread: 1.5, volley: 3, initialCooldown: 1, hitParticleId: 'hit-chunk', castStyle: 'throw' }),
  W({ id: 'chem-luot', name: 'Chém lướt', attack: 'dash', damage: 90, damageType: 'slash', range: 14, minRange: 3, cooldown: 7, windup: 0.25, knockback: 8, initialCooldown: 2, hitParticleId: 'spark', castStyle: 'swing' }),
  // ---- siege structures
  W({ id: 'none', name: 'Không tấn công', attack: 'melee', damage: 0, damageType: 'blunt', range: 0.3, cooldown: 60, windup: 0 }),
  W({ id: 'keep-arrows', name: 'Tên từ lỗ châu mai', attack: 'projectile', damage: 30, damageType: 'pierce', range: 40, cooldown: 1.4, windup: 0.2, knockback: 1, projectileId: 'arrow', projectileSpeed: 28, spread: 1.2, volley: 2, hitParticleId: 'hit-chunk' }),
  W({ id: 'tower-bow', name: 'Nỏ tháp cung', attack: 'projectile', damage: 28, damageType: 'pierce', range: 42, cooldown: 1.1, windup: 0.2, knockback: 1, projectileId: 'arrow', projectileSpeed: 30, spread: 1, volley: 2, hitParticleId: 'hit-chunk' }),
  W({ id: 'tower-gun', name: 'Súng tháp', attack: 'projectile', damage: 70, damageType: 'pierce', range: 38, cooldown: 2.2, windup: 0.3, knockback: 6, knockUp: 1.5, projectileId: 'bullet', projectileSpeed: 110, spread: 0.6, hitParticleId: 'hit-chunk', fireParticleId: 'muzzle-flash', areaParticleId: 'gun-smoke', castStyle: 'gun' }),
  W({ id: 'tesla-zap', name: 'Phóng điện', attack: 'chain', damage: 70, damageType: 'magic', range: 18, cooldown: 2.4, windup: 0.5, knockback: 3, chainCount: 4, chainRange: 6, chainFalloff: 0.8, stunDuration: 0.5, hitParticleId: 'lightning-spark', vfxColor: '#8fe4ff' }),
  // ---- skills
  W({ id: 'thien-loi', name: 'Thiên lôi (sét giáng)', attack: 'strike', damage: 140, damageType: 'magic', range: 32, cooldown: 9, windup: 0.8, knockback: 8, knockUp: 7, splashRadius: 3.2, strikeDelay: 0.45, stunDuration: 1.2, minTargets: 2, initialCooldown: 2, hitParticleId: 'lightning-spark', areaParticleId: 'shock-dust', vfxColor: '#a8dcff', castStyle: 'raise' }),
  W({ id: 'bao-sam', name: 'Bão sấm sét', attack: 'strike', damage: 75, damageType: 'magic', range: 34, cooldown: 18, windup: 1.1, knockback: 5, knockUp: 5, splashRadius: 2.6, strikeCount: 8, strikeDelay: 0.5, strikeInterval: 0.22, strikeSpread: 6.5, stunDuration: 0.8, minTargets: 4, initialCooldown: 4, hitParticleId: 'lightning-spark', areaParticleId: 'shock-dust', vfxColor: '#c9a8ff', castStyle: 'raise' }),
  W({ id: 'set-chuoi', name: 'Sét chuỗi (phóng từ tay)', attack: 'chain', damage: 70, damageType: 'magic', range: 18, cooldown: 7, windup: 0.45, knockback: 3, chainCount: 6, chainRange: 7, chainFalloff: 0.85, stunDuration: 0.7, minTargets: 2, initialCooldown: 1, hitParticleId: 'lightning-spark', vfxColor: '#7fe0ff', castStyle: 'palm' }),
  W({ id: 'phun-lua', name: 'Phun lửa', attack: 'breath', damage: 9, damageType: 'fire', range: 8, cooldown: 9, windup: 0.35, knockback: 1.5, cleaveArc: 40, maxTargets: 10, duration: 2.4, interval: 0.15, burnDps: 14, burnDuration: 3, minTargets: 2, initialCooldown: 1.5, fireParticleId: 'flame-jet', vfxColor: '#ff8a2a', castStyle: 'palm' }),
  W({ id: 'loc-xoay', name: 'Lốc xoáy', attack: 'vortex', damage: 28, damageType: 'blunt', range: 24, cooldown: 16, windup: 0.9, knockback: 16, knockUp: 10, splashRadius: 3.4, duration: 6.5, zoneSpeed: 3.2, pull: 9, lift: 9, minTargets: 3, initialCooldown: 3, hitParticleId: 'hit-dust', areaParticleId: 'whirl-dust', vfxColor: '#cfc6b4', castStyle: 'raise' }),
  W({ id: 'loc-lua', name: 'Lốc lửa', attack: 'vortex', damage: 36, damageType: 'fire', range: 22, cooldown: 18, windup: 0.9, knockback: 12, knockUp: 8, splashRadius: 3, duration: 5, zoneSpeed: 2.6, pull: 7, lift: 6, burnDps: 10, burnDuration: 2, minTargets: 3, initialCooldown: 4, areaParticleId: 'ember', vfxColor: '#ff6a1a', castStyle: 'raise' }),
  W({ id: 'thien-thach', name: 'Thiên thạch', attack: 'strike', damage: 240, damageType: 'fire', range: 40, minRange: 6, cooldown: 22, windup: 1.2, knockback: 20, knockUp: 11, splashRadius: 5, strikeVfx: 'meteor', strikeDelay: 1.3, burnDps: 12, burnDuration: 3, minTargets: 4, initialCooldown: 5, projectileId: 'meteor', hitParticleId: 'hit-dust', areaParticleId: 'ember', vfxColor: '#ff7a2a', castStyle: 'raise' }),
  W({ id: 'mua-thien-thach', name: 'Mưa thiên thạch', attack: 'strike', damage: 110, damageType: 'fire', range: 40, cooldown: 25, windup: 1, knockback: 12, knockUp: 8, splashRadius: 3.2, strikeVfx: 'meteor', strikeCount: 6, strikeDelay: 1.1, strikeInterval: 0.3, strikeSpread: 7, burnDps: 8, burnDuration: 2, minTargets: 5, initialCooldown: 6, projectileId: 'meteor', hitParticleId: 'hit-dust', areaParticleId: 'ember', vfxColor: '#ff7a2a' }),
  W({ id: 'dam-dat', name: 'Dậm đất (chấn động)', attack: 'nova', damage: 90, damageType: 'blunt', range: 3, cooldown: 9, windup: 0.55, knockback: 20, knockUp: 9, splashRadius: 5, stunDuration: 0.8, minTargets: 3, initialCooldown: 2, hitParticleId: 'hit-dust', areaParticleId: 'shock-dust', vfxColor: '#f0dfb4', castStyle: 'slam' }),
  W({ id: 'mua-ten', name: 'Mưa tên', attack: 'projectile', damage: 22, damageType: 'pierce', range: 36, cooldown: 12, windup: 0.9, knockback: 1, projectileId: 'arrow', projectileSpeed: 16, spread: 4.5, volley: 14, minTargets: 4, initialCooldown: 3, hitParticleId: 'hit-chunk', castStyle: 'bow' }),
  W({ id: 'mua-hoa-tien', name: 'Mưa hỏa tiễn', attack: 'projectile', damage: 18, damageType: 'fire', range: 36, cooldown: 14, windup: 1, knockback: 3, knockUp: 1, splashRadius: 2, projectileId: 'fire-arrow', projectileSpeed: 16, spread: 4, volley: 10, burnDps: 8, burnDuration: 2.5, minTargets: 4, initialCooldown: 3, castStyle: 'bow' }),
  W({ id: 'nem-tang-da', name: 'Ném tảng đá', attack: 'projectile', damage: 160, damageType: 'blunt', range: 26, minRange: 5, cooldown: 10, windup: 1, knockback: 22, knockUp: 10, splashRadius: 3.5, projectileId: 'boulder', projectileSpeed: 15, spread: 1, minTargets: 2, initialCooldown: 2, hitParticleId: 'hit-dust', castStyle: 'throw' }),
  W({ id: 'loat-dan', name: 'Loạt đạn liên thanh', attack: 'projectile', damage: 24, damageType: 'pierce', range: 30, cooldown: 11, windup: 0.4, knockback: 3, projectileId: 'bullet', projectileSpeed: 110, spread: 1.6, duration: 1.4, interval: 0.18, initialCooldown: 4, hitParticleId: 'hit-chunk', fireParticleId: 'muzzle-flash', areaParticleId: 'gun-smoke', castStyle: 'gun' }),
  W({ id: 'hoi-mau-dien-rong', name: 'Hồi máu diện rộng', attack: 'heal', damage: 55, damageType: 'magic', range: 10, cooldown: 10, windup: 0.8, splashRadius: 6, minTargets: 3, initialCooldown: 2, hitParticleId: 'heal', areaParticleId: 'heal-burst', vfxColor: '#b8ff9e', castStyle: 'raise' }),
];

const U = (u: Partial<UnitDef> & Pick<UnitDef, 'id' | 'name' | 'factionId' | 'role' | 'cost' | 'hp' | 'weaponId' | 'modelId'>): UnitDef => ({
  description: '',
  speed: 3.5,
  mass: 1,
  radius: 0.45,
  height: 1.8,
  armorClass: 'unarmored',
  riderModelId: null,
  skillIds: [],
  attackSpeed: 1,
  castSpeed: 1,
  flying: false,
  altitude: 0,
  blockChance: 0,
  chargeBonus: 1,
  knockbackResist: 0,
  trampleDamage: 0,
  structure: 'none',
  siegeSide: 'any',
  climbWalls: false,
  spawnUnitId: null,
  spawnInterval: 1,
  spawnMax: 10,
  // Units up to 150 are free starters; the rest unlock for about 20× their army cost, /100.
  unlockCost: u.cost <= 150 ? 0 : Math.round((u.cost * 20) / 1000) * 10,
  cardPrice: Math.min(5, Math.max(1, Math.round((Math.round(u.cost / 50) * 5) / 100))),
  starCards: [10, 20, 30, 40, 50],
  starCoins: [10, 20, 40, 80, 160],
  ...u,
});

/** Siege structure: immovable, siege armour. */
const S = (u: Partial<UnitDef> & Pick<UnitDef, 'id' | 'name' | 'cost' | 'hp' | 'modelId' | 'structure'>): UnitDef =>
  U({ factionId: 'thanh-tri', role: 'support', weaponId: 'none', speed: 0, mass: 500, armorClass: 'siege', knockbackResist: 1, ...u });

const units: UnitDef[] = [
  U({ id: 'clubber', name: 'Chiến binh gậy', factionId: 'bo-lac', role: 'melee', cost: 70, hp: 100, speed: 3.6, weaponId: 'club', modelId: 'm-clubber', description: 'Rẻ, đông, đập bừa.' }),
  U({ id: 'protector', name: 'Khiên bộ lạc', factionId: 'bo-lac', role: 'melee', cost: 90, hp: 160, speed: 3.2, armorClass: 'light', blockChance: 0.6, weaponId: 'small-club', modelId: 'm-protector', description: 'Khiên gỗ chặn tên rất tốt.' }),
  U({ id: 'spear-thrower', name: 'Người ném lao', factionId: 'bo-lac', role: 'ranged', cost: 120, hp: 70, speed: 3.4, weaponId: 'throw-spear', modelId: 'm-spear-thrower' }),
  U({ id: 'stoner', name: 'Người ném đá', factionId: 'bo-lac', role: 'ranged', cost: 80, hp: 70, speed: 3.4, weaponId: 'throw-stone', modelId: 'm-stoner' }),
  U({ id: 'chieftain', name: 'Tù trưởng', factionId: 'bo-lac', role: 'melee', cost: 450, hp: 700, speed: 3.8, mass: 2, radius: 0.55, height: 2.1, armorClass: 'light', knockbackResist: 0.4, skillIds: ['dam-dat'], weaponId: 'chief-axe', modelId: 'm-chieftain', description: 'Rìu quét nhiều mục tiêu.' }),
  U({ id: 'mammoth', name: 'Voi ma mút', factionId: 'bo-lac', role: 'melee', cost: 2200, hp: 4000, speed: 3, mass: 40, radius: 2.2, height: 4.2, armorClass: 'beast', knockbackResist: 0.9, trampleDamage: 60, skillIds: ['dam-dat'], weaponId: 'mammoth-tusks', modelId: 'm-mammoth', riderModelId: 'm-clubber', description: 'Giẫm nát mọi thứ.' }),
  U({ id: 'squire', name: 'Cận vệ', factionId: 'trung-co', role: 'melee', cost: 110, hp: 140, speed: 3.6, armorClass: 'light', blockChance: 0.35, weaponId: 'sword', modelId: 'm-squire' }),
  U({ id: 'archer', name: 'Cung thủ', factionId: 'trung-co', role: 'ranged', cost: 140, hp: 70, speed: 3.5, weaponId: 'bow', modelId: 'm-archer' }),
  U({ id: 'healer', name: 'Tu sĩ', factionId: 'trung-co', role: 'support', cost: 180, hp: 90, speed: 3.5, skillIds: ['hoi-mau-dien-rong'], weaponId: 'heal-staff', modelId: 'm-healer', description: 'Hồi máu đồng đội gần.' }),
  U({ id: 'knight', name: 'Hiệp sĩ', factionId: 'trung-co', role: 'melee', cost: 650, hp: 700, speed: 3.2, mass: 2, radius: 0.5, height: 1.9, armorClass: 'heavy', blockChance: 0.3, knockbackResist: 0.5, weaponId: 'knight-sword', modelId: 'm-knight' }),
  U({ id: 'cavalry', name: 'Kỵ binh', factionId: 'trung-co', role: 'melee', cost: 800, hp: 800, speed: 7, mass: 8, radius: 1, height: 2.6, armorClass: 'heavy', chargeBonus: 2.2, knockbackResist: 0.6, trampleDamage: 30, weaponId: 'lance', modelId: 'm-warhorse', riderModelId: 'm-rider-knight', description: 'Xung phong gây sát thương gấp đôi.' }),
  U({ id: 'catapult', name: 'Máy bắn đá', factionId: 'trung-co', role: 'siege', cost: 1000, hp: 500, speed: 1.4, mass: 20, radius: 1.6, height: 2.2, armorClass: 'siege', knockbackResist: 0.8, siegeSide: 'attack', weaponId: 'catapult', modelId: 'm-catapult', description: 'Bắn xa, nổ lan, không bắn được tầm gần.' }),
  U({ id: 'king', name: 'Nhà vua', factionId: 'trung-co', role: 'melee', cost: 1500, hp: 2200, speed: 3.4, mass: 3, radius: 0.6, height: 2.2, armorClass: 'heavy', knockbackResist: 0.6, skillIds: ['dam-dat'], weaponId: 'greatsword', modelId: 'm-king' }),
  U({ id: 'hoplite', name: 'Giáo binh', factionId: 'phuong-dong', role: 'melee', cost: 150, hp: 180, speed: 3.3, armorClass: 'light', blockChance: 0.5, weaponId: 'hoplite-spear', modelId: 'm-hoplite' }),
  U({ id: 'monk', name: 'Võ tăng', factionId: 'phuong-dong', role: 'melee', cost: 250, hp: 220, speed: 5.5, weaponId: 'monk-staff', modelId: 'm-monk', description: 'Nhanh, đánh liên hoàn.' }),
  U({ id: 'fire-archer', name: 'Hỏa tiễn thủ', factionId: 'phuong-dong', role: 'ranged', cost: 400, hp: 80, speed: 3.5, skillIds: ['mua-hoa-tien'], weaponId: 'fire-bow', modelId: 'm-fire-archer' }),
  U({ id: 'war-elephant', name: 'Chiến tượng', factionId: 'phuong-dong', role: 'melee', cost: 2000, hp: 3000, speed: 3.2, mass: 40, radius: 2, height: 4, armorClass: 'beast', knockbackResist: 0.9, trampleDamage: 50, skillIds: ['mua-ten'], weaponId: 'elephant-bow', modelId: 'm-war-elephant' }),
  U({ id: 'eagle', name: 'Đại bàng', factionId: 'huyen-thoai', role: 'melee', cost: 300, hp: 150, speed: 8, mass: 0.8, radius: 0.8, height: 1.2, armorClass: 'beast', flying: true, altitude: 7, weaponId: 'talons', modelId: 'm-eagle', description: 'Bay, bổ nhào xuống cào.' }),
  U({ id: 'wizard', name: 'Pháp sư', factionId: 'huyen-thoai', role: 'ranged', cost: 700, hp: 120, speed: 3.4, skillIds: ['thien-thach'], weaponId: 'fireball-staff', modelId: 'm-wizard' }),
  U({ id: 'giant', name: 'Người khổng lồ', factionId: 'huyen-thoai', role: 'melee', cost: 1600, hp: 2500, speed: 3.4, mass: 25, radius: 1.3, height: 4.6, armorClass: 'beast', knockbackResist: 0.7, trampleDamage: 20, skillIds: ['nem-tang-da', 'dam-dat'], weaponId: 'giant-club', modelId: 'm-giant', description: 'Một gậy bay cả hàng.' }),
  U({ id: 'dragon', name: 'Rồng lửa', factionId: 'huyen-thoai', role: 'ranged', cost: 5000, hp: 6000, speed: 5, mass: 50, radius: 3, height: 3, armorClass: 'beast', flying: true, altitude: 9, knockbackResist: 0.95, skillIds: ['mua-thien-thach'], weaponId: 'dragon-breath', modelId: 'm-dragon', description: 'Phun lửa từ trên cao.' }),
  U({ id: 'baby-dragon', name: 'Rồng Xanh', factionId: 'huyen-thoai', role: 'ranged', cost: 1200, hp: 1400, speed: 5.5, mass: 8, radius: 1.4, height: 2.4, armorClass: 'beast', flying: true, altitude: 6, knockbackResist: 0.6, weaponId: 'baby-dragon-breath', modelId: 'm-baby-dragon', description: 'Rồng con mập ú, bay thấp phun lửa thiêu cả nhóm.' }),
  U({ id: 'raptor', name: 'Khủng long Raptor', factionId: 'huyen-thoai', role: 'melee', cost: 380, hp: 260, speed: 6.4, mass: 1.4, radius: 0.9, height: 2, armorClass: 'beast', chargeBonus: 1.6, knockbackResist: 0.15, weaponId: 'raptor-bite', modelId: 'm-raptor', description: 'Săn theo bầy, lao vào cắn xé cực nhanh.' }),
  U({ id: 't-rex', name: 'Khủng long T-Rex', factionId: 'huyen-thoai', role: 'melee', cost: 2500, hp: 3000, speed: 4.5, mass: 60, radius: 2.6, height: 5.2, armorClass: 'beast', chargeBonus: 1.5, knockbackResist: 0.7, trampleDamage: 50, skillIds: ['dam-dat'], weaponId: 'rex-bite', modelId: 'm-t-rex', description: 'Bạo chúa săn mồi, một ngoạm bay cả hàng, giẫm nát mọi thứ.' }),
  U({ id: 'stegosaurus', name: 'Khủng long Stegosaurus', factionId: 'huyen-thoai', role: 'melee', cost: 1400, hp: 2200, speed: 2.9, mass: 25, radius: 1.8, height: 3.4, armorClass: 'beast', knockbackResist: 0.75, trampleDamage: 25, weaponId: 'stego-tail', modelId: 'm-stegosaurus', description: 'Pháo đài gai, đuôi quật quét sạch xung quanh.' }),
  U({ id: 'parasaurolophus', name: 'Khủng long Parasaurolophus', factionId: 'huyen-thoai', role: 'melee', cost: 550, hp: 550, speed: 6.8, mass: 3, radius: 1, height: 2.4, armorClass: 'beast', chargeBonus: 2.2, knockbackResist: 0.2, trampleDamage: 20, weaponId: 'para-tail', modelId: 'm-parasaurolophus', description: 'Ăn cỏ hiền lành nhưng húc cực mạnh khi bị dồn vào chân tường.' }),
  U({ id: 'triceratops', name: 'Khủng long Triceratops', factionId: 'huyen-thoai', role: 'melee', cost: 1200, hp: 1900, speed: 4.8, mass: 22, radius: 1.7, height: 3.6, armorClass: 'beast', chargeBonus: 2, knockbackResist: 0.7, trampleDamage: 30, weaponId: 'tri-horns', modelId: 'm-triceratops', description: 'Xe tăng ba sừng, húc bay mọi thứ dám cản đường.' }),
  U({ id: 'musketeer', name: 'Lính hỏa mai', factionId: 'trung-co', role: 'ranged', cost: 260, hp: 80, speed: 3.3, skillIds: ['loat-dan'], weaponId: 'musket', modelId: 'm-musketeer', description: 'Đạn bay thẳng, xuyên giáp nhẹ; thỉnh thoảng xả loạt đạn liên thanh.' }),
  U({ id: 'wind-shaman', name: 'Pháp sư gió', factionId: 'bo-lac', role: 'support', cost: 650, hp: 150, speed: 3.4, skillIds: ['loc-xoay'], weaponId: 'heal-staff', modelId: 'm-wind-shaman', description: 'Hồi máu đồng đội, gọi lốc xoáy hút bổng quân địch.' }),
  U({ id: 'pyromancer', name: 'Hỏa thuật sư', factionId: 'phuong-dong', role: 'ranged', cost: 800, hp: 170, speed: 3.5, skillIds: ['phun-lua', 'loc-lua'], weaponId: 'fireball-staff', modelId: 'm-pyromancer', description: 'Phun lửa từ tay, triệu hồi lốc lửa thiêu cháy.' }),
  U({ id: 'thunder-mage', name: 'Lôi pháp sư', factionId: 'huyen-thoai', role: 'ranged', cost: 900, hp: 140, speed: 3.4, skillIds: ['set-chuoi', 'thien-loi'], weaponId: 'zap', modelId: 'm-thunder-mage', description: 'Sét chuỗi từ tay, gọi thiên lôi giáng xuống.' }),
  U({ id: 'storm-lord', name: 'Thần sấm', factionId: 'huyen-thoai', role: 'ranged', cost: 2600, hp: 1800, speed: 3.6, mass: 3, radius: 0.7, height: 2.5, armorClass: 'heavy', knockbackResist: 0.7, castSpeed: 1.2, skillIds: ['bao-sam', 'set-chuoi', 'thien-loi'], weaponId: 'zap', modelId: 'm-storm-lord', description: 'Gọi bão sấm sét phủ kín chiến trường.' }),
  U({ id: 'ninja', name: 'Ninja áo đen', factionId: 'phuong-dong', role: 'melee', cost: 300, hp: 170, speed: 5.8, climbWalls: true, siegeSide: 'attack', skillIds: ['chem-luot', 'phi-tieu'], weaponId: 'katana', modelId: 'm-ninja', description: 'Leo qua tường thành, chém lướt vào cung thủ trên tường.' }),
  U({ id: 'fire-catapult', name: 'Máy bắn đá lửa', factionId: 'phuong-dong', role: 'siege', cost: 1300, hp: 550, speed: 1.3, mass: 20, radius: 1.6, height: 2.2, armorClass: 'siege', knockbackResist: 0.8, siegeSide: 'attack', weaponId: 'fire-catapult', modelId: 'm-fire-catapult', description: 'Ném hũ dầu nổ lửa, thiêu cháy tường và quân thủ.' }),
  // ---- siege structures (speed 0, immovable)
  S({ id: 'tuong-thanh', name: 'Tường đá', structure: 'wall', siegeSide: 'defense', cost: 25, hp: 400, radius: 1.45, height: 2, modelId: 'm-wall', unlockCost: 0, description: 'Khối 4×2×2 m, xếp chồng 3 tầng. Lính phe thủ đứng và đi lại trên mặt tường.' }),
  S({ id: 'tuong-gach', name: 'Tường gạch', structure: 'wall', siegeSide: 'defense', cost: 25, hp: 400, radius: 1.45, height: 2, modelId: 'm-brick-wall', unlockCost: 0, description: 'Khối 4×2×2 m, xếp chồng 3 tầng. Lính phe thủ đứng và đi lại trên mặt tường.' }),
  S({ id: 'thap-canh', name: 'Tháp canh', structure: 'platform', siegeSide: 'defense', cost: 200, hp: 1800, radius: 1.45, height: 6, modelId: 'm-watchtower', description: 'Sàn cho 2 lính, tăng 30% tầm bắn cho lính đứng trên.' }),
  S({ id: 'thap-cung', name: 'Tháp cung', structure: 'building', siegeSide: 'defense', cost: 400, hp: 1600, radius: 1.5, height: 7, weaponId: 'tower-bow', modelId: 'm-bow-tower', description: 'Bắn loạt 2 mũi tên, tầm xa.' }),
  S({ id: 'thap-sung', name: 'Tháp súng', structure: 'building', siegeSide: 'defense', cost: 550, hp: 1800, radius: 1.5, height: 6.5, weaponId: 'tower-gun', modelId: 'm-gun-tower', description: 'Đạn chì mạnh, xuyên giáp nhẹ.' }),
  S({ id: 'tru-dien', name: 'Trụ phóng điện', structure: 'building', siegeSide: 'defense', cost: 700, hp: 1400, radius: 1.2, height: 6, weaponId: 'tesla-zap', modelId: 'm-tesla', description: 'Sét chuỗi lan nhiều mục tiêu, gây choáng.' }),
  S({ id: 'nha-linh', name: 'Nhà lính', structure: 'building', siegeSide: 'any', cost: 600, hp: 2200, radius: 2.4, height: 4.5, spawnUnitId: 'clubber', modelId: 'm-barracks', description: 'Mỗi giây sinh 1 lính, tối đa 10 lính còn sống.' }),
  S({ id: 'nha-chinh', name: 'Nhà chính', structure: 'core', siegeSide: 'defense', cost: 50, hp: 6000, radius: 3.2, height: 9, weaponId: 'keep-arrows', modelId: 'm-keep', unlockCost: 0, description: 'Bắt buộc có 1. Bị phá là phe thủ thua.' }),
];

const A = (a: Omit<AssetDef, 'scale' | 'seed' | 'sculpt' | 'glb'> & Partial<Pick<AssetDef, 'scale' | 'seed' | 'sculpt' | 'glb'>>): AssetDef => ({ scale: 1, seed: 1, sculpt: null, glb: null, ...a });

const assets: AssetDef[] = [
  A({ id: 'm-clubber', name: 'Chiến binh gậy', kind: 'humanoid', params: { skin: '#e2a878', shirt: '#8a5a2b', pants: '#6b4424', armor: 'loincloth', armorColor: '#a8743c', hair: 'short', hairColor: '#2a1a10', weapon: 'club' } }),
  A({ id: 'm-protector', name: 'Khiên bộ lạc', kind: 'humanoid', params: { skin: '#e2a878', shirt: '#7a4a24', pants: '#5a3a1e', armor: 'fur', armorColor: '#9a7048', head: 'headband', headColor: '#c8692f', hair: 'long', weapon: 'club', offhand: 'shield-round', shieldColor: '#a0672e' } }),
  A({ id: 'm-spear-thrower', name: 'Người ném lao', kind: 'humanoid', params: { skin: '#d99a6c', shirt: '#9a6a3a', armor: 'loincloth', armorColor: '#c8692f', head: 'headband', headColor: '#d8323a', hair: 'long', weapon: 'spear' } }),
  A({ id: 'm-stoner', name: 'Người ném đá', kind: 'humanoid', params: { skin: '#e2a878', shirt: '#8a6a44', armor: 'loincloth', hair: 'mohawk', hairColor: '#c8692f', weapon: 'stone' } }),
  A({ id: 'm-chieftain', name: 'Tù trưởng', kind: 'humanoid', scale: 1.15, params: { bulk: 1.3, skin: '#d99a6c', shirt: '#6b3a1e', armor: 'fur', armorColor: '#e8dcc0', head: 'headband', headColor: '#f2c230', hair: 'long', hairColor: '#1a1008', beard: 'long', cape: true, capeColor: '#7a2a10', weapon: 'axe' } }),
  A({ id: 'm-squire', name: 'Cận vệ', kind: 'humanoid', params: { shirt: '#3b6fd6', pants: '#3a3a4a', armor: 'vest', armorColor: '#c8cdd4', head: 'helmet', headColor: '#aab2bc', weapon: 'sword', offhand: 'shield-kite', shieldColor: '#2f5fb3' } }),
  A({ id: 'm-archer', name: 'Cung thủ', kind: 'humanoid', params: { shirt: '#2f7a3a', pants: '#4a3b2a', head: 'hood', headColor: '#2f6a34', hair: 'short', weapon: 'bow' } }),
  A({ id: 'm-healer', name: 'Tu sĩ', kind: 'humanoid', params: { shirt: '#f0ead6', armor: 'robe', armorColor: '#f0ead6', hair: 'topknot', hairColor: '#8a6a44', brows: 'worried', weapon: 'staff', orbColor: '#9dff7a' } }),
  A({ id: 'm-knight', name: 'Hiệp sĩ', kind: 'humanoid', scale: 1.05, params: { bulk: 1.15, shirt: '#2f5fb3', pants: '#4a4f58', armor: 'plate', armorColor: '#c9ced6', head: 'greathelm', headColor: '#b8bec7', cape: true, capeColor: '#2f5fb3', weapon: 'sword', offhand: 'shield-kite', shieldColor: '#2f5fb3' } }),
  A({ id: 'm-rider-knight', name: 'Kỵ sĩ', kind: 'humanoid', params: { shirt: '#2f5fb3', pants: '#4a4f58', armor: 'plate', armorColor: '#c9ced6', head: 'helmet', headColor: '#b8bec7', cape: true, capeColor: '#2f5fb3', weapon: 'lance' } }),
  A({ id: 'm-king', name: 'Nhà vua', kind: 'humanoid', scale: 1.2, params: { bulk: 1.3, shirt: '#7a1fa2', pants: '#3a2a4a', armor: 'plate', armorColor: '#d4af37', head: 'crown', headColor: '#f2c230', hair: 'long', hairColor: '#d8d8d8', beard: 'long', cape: true, capeColor: '#b3262e', weapon: 'greatsword' } }),
  A({ id: 'm-hoplite', name: 'Giáo binh', kind: 'humanoid', params: { shirt: '#d23c3c', pants: '#6b2a1e', armor: 'plate', armorColor: '#c89a3a', head: 'helmet', headColor: '#c89a3a', hair: 'none', weapon: 'spear', offhand: 'shield-round', shieldColor: '#c89a3a' } }),
  A({ id: 'm-monk', name: 'Võ tăng', kind: 'humanoid', params: { skin: '#e8b88a', shirt: '#f0a020', pants: '#c8781a', armor: 'robe', armorColor: '#f0a020', hair: 'none', weapon: 'staff', orbColor: '#8a5a2b' } }),
  A({ id: 'm-fire-archer', name: 'Hỏa tiễn thủ', kind: 'humanoid', params: { shirt: '#d23c3c', pants: '#3a2a2a', head: 'strawhat', headColor: '#d8b25a', hair: 'short', weapon: 'bow' }, glb: { url: '/models/hoa-tien-thu.glb', fileName: 'hoa tien thu.glb', uploadedAt: 0, tint: {}, hide: ['Revolver', 'Revolver_Small', 'Pistol', 'GrenadeLauncher', 'ShortCannon', 'Shotgun', 'Sniper_2', 'Sniper', 'SMG', 'AK', 'Shovel', 'Knife_1', 'Knife_2'] } }),
  A({ id: 'm-archer-east', name: 'Cung thủ trên voi', kind: 'humanoid', params: { shirt: '#d23c3c', pants: '#3a2a2a', head: 'headband', headColor: '#f2c230', weapon: 'bow' } }),
  A({ id: 'm-wizard', name: 'Pháp sư', kind: 'humanoid', scale: 0.9, params: { shirt: '#4a2a8a', armor: 'robe', armorColor: '#4a2a8a', head: 'wizard', headColor: '#3a2070', hair: 'long', hairColor: '#e8e8e8', beard: 'long', weapon: 'staff', orbColor: '#ff7a1a' }, glb: { url: '/models/phap-su.glb', fileName: 'phap su.glb', uploadedAt: 0, tint: { Wizard_Texture: { from: '#2e44a8', to: '#4a2a8a' } }, hide: [] } }),
  A({ id: 'm-giant', name: 'Người khổng lồ', kind: 'humanoid', scale: 2.5, params: { bulk: 1.4, skin: '#c9a27a', shirt: '#7a6a4a', pants: '#5a4a32', armor: 'loincloth', armorColor: '#6b4424', hair: 'none', beard: 'short', hairColor: '#4a3020', weapon: 'bigclub' } }),
  A({ id: 'm-warhorse', name: 'Chiến mã', kind: 'horse', params: { coat: '#6b4226', mane: '#1e140c', barding: true, bardingColor: '#2f5fb3' } }),
  A({ id: 'm-mammoth', name: 'Voi ma mút', kind: 'elephant', scale: 0.55, params: { skin: '#8c9591', fur: true, tusks: true, tuskColor: '#f1ead8', howdah: false }, glb: { url: '/models/voi.glb', fileName: 'voi.glb', uploadedAt: 0, tint: {}, hide: [] } }),
  A({ id: 'm-war-elephant', name: 'Chiến tượng', kind: 'elephant', scale: 0.5, params: { skin: '#8d8f96', tusks: true, howdah: false, blanket: '#d23c3c' }, glb: { url: '/models/voi.glb', fileName: 'voi.glb', uploadedAt: 0, tint: {}, hide: [] } }),
  A({ id: 'm-eagle', name: 'Đại bàng', kind: 'bird', scale: 1.4, params: {} }),
  A({ id: 'm-raptor', name: 'Khủng long Raptor', kind: 'raptor', params: { body: '#5f9e4d', belly: '#d9cf9e', back: '#3c6e35', eye: '#ffd23f' }, glb: { url: '/models/velociraptor.glb', fileName: 'Velociraptor by Quaternius.glb', uploadedAt: 0, tint: {}, hide: [] } }),
  A({ id: 'm-t-rex', name: 'Khủng long T-Rex', kind: 'raptor', scale: 2.6, params: { body: '#8a6a4a', belly: '#d9c49a', back: '#5a422a', eye: '#ffd23f' }, glb: { url: '/models/t-rex.glb', fileName: 'T-Rex by Quaternius.glb', uploadedAt: 0, tint: {}, hide: [] } }),
  A({ id: 'm-stegosaurus', name: 'Khủng long Stegosaurus', kind: 'raptor', scale: 1.7, params: { body: '#5f8e4d', belly: '#cfc48f', back: '#3c6e35', eye: '#2a2018' }, glb: { url: '/models/stegosaurus.glb', fileName: 'Stegosaurus by Quaternius.glb', uploadedAt: 0, tint: {}, hide: [] } }),
  A({ id: 'm-parasaurolophus', name: 'Khủng long Parasaurolophus', kind: 'raptor', scale: 1.2, params: { body: '#7fae5a', belly: '#e3d9a8', back: '#4a7a3a', eye: '#3a2a1a' }, glb: { url: '/models/parasaurolophus.glb', fileName: 'Parasaurolophus by Quaternius.glb', uploadedAt: 0, tint: {}, hide: [] } }),
  A({ id: 'm-triceratops', name: 'Khủng long Triceratops', kind: 'raptor', scale: 1.8, params: { body: '#8a7a5a', belly: '#d9cfa8', back: '#5a4a32', eye: '#2a2018' }, glb: { url: '/models/triceratops.glb', fileName: 'Triceratops by Quaternius.glb', uploadedAt: 0, tint: {}, hide: [] } }),
  A({ id: 'm-dragon', name: 'Rồng lửa', kind: 'dragon', params: {} }),
  A({ id: 'm-baby-dragon', name: 'Rồng Xanh', kind: 'dragon', scale: 1.2, params: { type: 'baby', body: '#8cc540', belly: '#a4d257', wing: '#a0583a', horn: '#9b5a3c', eye: '#7a4a20' }, glb: { url: '/models/rong-xanh.glb', fileName: 'rong xanh.glb', uploadedAt: 0, tint: { Main: '#8cc540', Belly: '#a4d257', Wings: '#a0583a', Claws: '#9b5a3c', Eyes: '#7a4a20' }, hide: [] } }),
  A({ id: 'm-catapult', name: 'Máy bắn đá', kind: 'catapult', params: {} }),
  A({ id: 'm-musketeer', name: 'Lính hỏa mai', kind: 'humanoid', params: { shirt: '#2f5fb3', pants: '#e8e0cc', boots: '#1e1a16', armor: 'vest', armorColor: '#8a1f24', head: 'cap', headColor: '#1e2a44', hair: 'long', hairColor: '#d8d0c0', weapon: 'musket', woodColor: '#6b4424', metalColor: '#8a8f96' } }),
  A({ id: 'm-wind-shaman', name: 'Pháp sư gió', kind: 'humanoid', scale: 0.9, params: { skin: '#d99a6c', shirt: '#6a8a7a', pants: '#5a4a32', armor: 'fur', armorColor: '#d8d0b8', head: 'headband', headColor: '#4fb3a8', hair: 'long', hairColor: '#e8e8e8', beard: 'short', brows: 'worried', weapon: 'staff', orbColor: '#c8fff0', woodColor: '#9a7a4a' }, glb: { url: '/models/phap-su.glb', fileName: 'phap su.glb', uploadedAt: 0, tint: { Wizard_Texture: { from: '#2e44a8', to: '#e8e8e8' } }, hide: [] } }),
  A({ id: 'm-pyromancer', name: 'Hỏa thuật sư', kind: 'humanoid', scale: 0.9, params: { skin: '#e8b88a', shirt: '#b3262e', armor: 'robe', armorColor: '#9a1f1f', head: 'hood', headColor: '#4a0f0f', hair: 'none', weapon: 'none' }, glb: { url: '/models/phap-su.glb', fileName: 'phap su.glb', uploadedAt: 0, tint: { Wizard_Texture: { from: '#2e44a8', to: '#b3262e' } }, hide: [] } }),
  A({ id: 'm-thunder-mage', name: 'Lôi pháp sư', kind: 'humanoid', scale: 0.9, params: { shirt: '#2a3f8a', armor: 'robe', armorColor: '#26357a', head: 'wizard', headColor: '#1a2560', hair: 'long', hairColor: '#e8e8e8', beard: 'long', weapon: 'staff', orbColor: '#8fe4ff', woodColor: '#3a3048' }, glb: { url: '/models/phap-su.glb', fileName: 'phap su.glb', uploadedAt: 0, tint: { Wizard_Texture: { from: '#2e44a8', to: '#2a5aff' } }, hide: [] } }),
  A({ id: 'm-storm-lord', name: 'Thần sấm', kind: 'humanoid', scale: 1.2, params: { bulk: 1.3, skin: '#e8c0a0', shirt: '#4a2a8a', pants: '#2a2440', armor: 'plate', armorColor: '#b8c4d8', head: 'horned', headColor: '#c9ced6', hair: 'long', hairColor: '#f2d27a', beard: 'long', cape: true, capeColor: '#b3262e', weapon: 'hammer', metalColor: '#dfe6f0', woodColor: '#5a3a24' }, glb: { url: '/models/phap-su.glb', fileName: 'phap su.glb', uploadedAt: 0, tint: { Wizard_Texture: { from: '#2e44a8', to: '#c8922a' } }, hide: [] } }),
  A({ id: 'm-ninja', name: 'Ninja áo đen', kind: 'humanoid', scale: 0.9, params: { skin: '#e8b88a', shirt: '#17171b', pants: '#17171b', boots: '#0e0e10', armor: 'none', head: 'ninja', headColor: '#121215', hair: 'none', brows: 'angry', weapon: 'katana', metalColor: '#dfe6ee', woodColor: '#2a2a2e' }, glb: { url: '/models/ninja.glb', fileName: 'ninja.glb', uploadedAt: 0, tint: {}, hide: [] } }),
  A({ id: 'm-fire-catapult', name: 'Máy bắn đá lửa', kind: 'catapult', params: { wood: '#6b3f22', metal: '#3f3a36', rope: '#b89a5a', fire: true } }),
  A({ id: 'm-wall', name: 'Tường đá', kind: 'structure', params: { type: 'wall', stone: '#cfd3d8', stone2: '#9aa0a8', wallLength: 2, wallHeight: 2, wallDepth: 2 } }),
  A({ id: 'm-brick-wall', name: 'Tường gạch', kind: 'structure', params: { type: 'brick-wall', stone: '#c08c3a', stone2: '#8a5f24', accent: '#1e1a16', wallLength: 2, wallHeight: 2, wallDepth: 2 } }),
  A({ id: 'm-watchtower', name: 'Tháp canh', kind: 'structure', params: { type: 'watchtower' } }),
  A({ id: 'm-bow-tower', name: 'Tháp cung', kind: 'structure', params: { type: 'bow-tower', roof: '#2f5f9a' } }),
  A({ id: 'm-gun-tower', name: 'Tháp súng', kind: 'structure', params: { type: 'gun-tower', roof: '#4a4f58' } }),
  A({ id: 'm-tesla', name: 'Trụ phóng điện', kind: 'structure', params: { type: 'tesla', accent: '#7fe0ff' } }),
  A({ id: 'm-barracks', name: 'Nhà lính', kind: 'structure', scale: 3.3, params: { type: 'barracks', roof: '#6b4a2e', accent: '#8a2a2a' } }),
  A({ id: 'm-keep', name: 'Nhà chính', kind: 'structure', scale: 4.2, params: { type: 'keep', roof: '#b3262e' } }),
  A({ id: 'tree-pine', name: 'Cây thông', kind: 'tree', scale: 2.7, params: { type: 'pine', leaf: '#2f6a3a', leaf2: '#3f7f42', height: 7 }, glb: { url: '/models/cay-thong.glb', fileName: 'cay thong.glb', uploadedAt: 0, tint: {}, hide: [] } }),
  A({ id: 'tree-oak', name: 'Cây sồi', kind: 'tree', scale: 2, params: { type: 'oak', leaf: '#3f8a3a', leaf2: '#5fa845', height: 6 }, glb: { url: '/models/cay-soi.glb', fileName: 'cay soi.glb', uploadedAt: 0, tint: {}, hide: [] } }),
  A({ id: 'tree-snow', name: 'Thông phủ tuyết', kind: 'tree', scale: 1.2, seed: 4, params: { type: 'pine', trunk: '#5a4636', leaf: '#e6eef3', leaf2: '#3f6a4a', height: 7 }, glb: { url: '/models/thong-phu-tuyet.glb', fileName: 'thong phu tuyet.glb', uploadedAt: 0, tint: {}, hide: [] } }),
  A({ id: 'tree-birch', name: 'Cây bạch dương', kind: 'tree', scale: 1.2, params: { type: 'birch', trunk: '#e8e4da', leaf: '#8fbf4a', leaf2: '#b4d25a', height: 6.5 }, glb: { url: '/models/cay-bach-duong.glb', fileName: 'cay bach duong.glb', uploadedAt: 0, tint: {}, hide: [] } }),
  A({ id: 'tree-dead', name: 'Cây khô', kind: 'tree', scale: 1.7, params: { type: 'dead', trunk: '#5a4636', height: 5 }, glb: { url: '/models/cay-kho.glb', fileName: 'cay kho.glb', uploadedAt: 0, tint: {}, hide: [] } }),
  A({ id: 'tree-palm', name: 'Cây cọ', kind: 'tree', scale: 1.75, params: { type: 'palm', trunk: '#9a7a4a', leaf: '#4f9a3f', leaf2: '#6fb44a', height: 7 }, glb: { url: '/models/cay-co.glb', fileName: 'cay co.glb', uploadedAt: 0, tint: {}, hide: [] } }),
  A({ id: 'tree-cactus', name: 'Xương rồng', kind: 'tree', scale: 4.8, params: { type: 'cactus', leaf: '#4f8a3a', leaf2: '#6fa84a', height: 3 }, glb: { url: '/models/xuong-rong.glb', fileName: 'xuong rong.glb', uploadedAt: 0, tint: {}, hide: [] } }),
  A({ id: 'rock-gray', name: 'Đá xám', kind: 'rock', params: { color: '#8b8d90', color2: '#6f7276' } }),
  A({ id: 'rock-mossy', name: 'Đá rêu', kind: 'rock', seed: 7, params: { color: '#7d8a74', color2: '#5f7a4a', roughness: 0.45 } }),
  A({ id: 'rock-sand', name: 'Đá sa thạch', kind: 'rock', scale: 1.2, seed: 3, params: { color: '#c89a68', color2: '#a87a4a', flatness: 0.55 }, glb: { url: '/models/da-sa-thach.glb', fileName: 'da sa thach.glb', uploadedAt: 0, tint: {}, hide: [] } }),
  A({ id: 'bush-green', name: 'Bụi cỏ', kind: 'bush', scale: 0.4, params: {}, glb: { url: '/models/bui-co.glb', fileName: 'bui co.glb', uploadedAt: 0, tint: {}, hide: [] } }),
  A({ id: 'bush-berry', name: 'Bụi quả mọng', kind: 'bush', scale: 0.23, seed: 5, params: { berries: true }, glb: { url: '/models/bui-qua-mong.glb', fileName: 'bui qua mong.glb', uploadedAt: 0, tint: {}, hide: [] } }),
  A({ id: 'bush-dry', name: 'Bụi khô', kind: 'bush', scale: 0.5, seed: 9, params: { leaf: '#a89a5a', leaf2: '#c8b46a' }, glb: { url: '/models/bui-kho.glb', fileName: 'bui kho.glb', uploadedAt: 0, tint: {}, hide: [] } }),
];

const M = (m: Partial<MapDef> & Pick<MapDef, 'id' | 'name' | 'seed'>): MapDef => ({
  size: 140,
  heightScale: 3,
  hilliness: 1,
  river: { enabled: false, width: 8, meander: 10, ford: 0 },
  rise: 0,
  trees: { perHectare: 10, kinds: ['tree-oak'] },
  rocks: { perHectare: 6, kinds: ['rock-gray'] },
  bushes: { perHectare: 25, kinds: ['bush-green'] },
  grassColor: '#6fae4b',
  dirtColor: '#8a6a3f',
  sandColor: '#d9c58a',
  waterColor: '#3a8fd0',
  skyTop: '#5aa8f0',
  skyBottom: '#d6ecff',
  fog: 0.25,
  deployDepth: 28,
  defenseDepth: 0,
  budget: 3000,
  ...m,
});

const maps: MapDef[] = [
  M({ id: 'dong-co', name: 'Đồng cỏ', seed: 1234, trees: { perHectare: 12, kinds: ['tree-oak', 'tree-birch'] }, bushes: { perHectare: 30, kinds: ['bush-green', 'bush-berry'] } }),
  M({ id: 'song-xanh', name: 'Dòng sông', seed: 777, size: 150, heightScale: 3.5, river: { enabled: true, width: 9, meander: 12, ford: 0 }, trees: { perHectare: 16, kinds: ['tree-oak', 'tree-pine'] }, rocks: { perHectare: 10, kinds: ['rock-gray', 'rock-mossy'] }, bushes: { perHectare: 30, kinds: ['bush-green'] }, grassColor: '#62a34a', budget: 4000 }),
  M({ id: 'rung-thong', name: 'Rừng thông', seed: 4242, heightScale: 5, hilliness: 1.4, trees: { perHectare: 55, kinds: ['tree-pine'] }, rocks: { perHectare: 12, kinds: ['rock-mossy', 'rock-gray'] }, bushes: { perHectare: 20, kinds: ['bush-green'] }, grassColor: '#4f8f45', skyTop: '#6a9ccc', skyBottom: '#dfe9ef', fog: 0.45, budget: 5000 }),
  // ---- made for sieges (the red side has room for a castle)
  M({ id: 'thanh-tren-doi', name: 'Thành trên đồi', seed: 3131, size: 150, heightScale: 2.2, hilliness: 0.9, rise: 9, trees: { perHectare: 6, kinds: ['tree-oak', 'tree-pine'] }, rocks: { perHectare: 8, kinds: ['rock-gray', 'rock-mossy'] }, bushes: { perHectare: 18, kinds: ['bush-green'] }, grassColor: '#6aa84a', defenseDepth: 56, budget: 5000 }),
  M({ id: 'deo-song', name: 'Đèo sông', seed: 5150, size: 160, heightScale: 3, hilliness: 1.1, river: { enabled: true, width: 11, meander: 4, ford: 14 }, trees: { perHectare: 12, kinds: ['tree-pine', 'tree-oak'] }, rocks: { perHectare: 12, kinds: ['rock-mossy', 'rock-gray'] }, bushes: { perHectare: 20, kinds: ['bush-green'] }, grassColor: '#5e9e48', defenseDepth: 50, budget: 5000 }),
  M({ id: 'thanh-sa-mac', name: 'Thành sa mạc', seed: 7272, size: 160, heightScale: 1.5, hilliness: 0.6, trees: { perHectare: 2, kinds: ['tree-palm', 'tree-cactus'] }, rocks: { perHectare: 4, kinds: ['rock-sand'] }, bushes: { perHectare: 4, kinds: ['bush-dry'] }, grassColor: '#dcbc78', dirtColor: '#c29a58', sandColor: '#ecd9a4', skyTop: '#6fb6f2', skyBottom: '#fff1d6', fog: 0.15, defenseDepth: 58, budget: 6000 }),
  M({ id: 'thanh-tuyet', name: 'Thành tuyết', seed: 8484, size: 150, heightScale: 4, hilliness: 1.2, trees: { perHectare: 22, kinds: ['tree-snow', 'tree-pine'] }, rocks: { perHectare: 8, kinds: ['rock-gray'] }, bushes: { perHectare: 0, kinds: [] }, grassColor: '#e8eef2', dirtColor: '#9aa3ad', sandColor: '#cfd8df', waterColor: '#6fa8c8', skyTop: '#9fb4c8', skyBottom: '#eef3f7', fog: 0.6, defenseDepth: 54, budget: 5000 }),
  M({ id: 'sa-mac', name: 'Sa mạc', seed: 9001, size: 160, heightScale: 4, hilliness: 0.8, trees: { perHectare: 6, kinds: ['tree-palm', 'tree-cactus'] }, rocks: { perHectare: 14, kinds: ['rock-sand'] }, bushes: { perHectare: 8, kinds: ['bush-dry'] }, grassColor: '#d8b870', dirtColor: '#c29a58', sandColor: '#e8d39a', skyTop: '#6fb6f2', skyBottom: '#fff1d6', fog: 0.2, budget: 6000 }),
];

const bots: BotDef[] = [
  { id: 'de', name: 'Dễ', description: 'Quân ít tiền, đánh lộn xộn.', difficulty: 1, budgetMultiplier: 0.8, strategy: 'balanced', factionIds: [], reactive: false, formation: 'scatter', randomness: 0.8, maxUnits: 60 },
  { id: 'thuong', name: 'Thường', description: 'Đội hình cân bằng, ngang tiền.', difficulty: 2, budgetMultiplier: 1, strategy: 'balanced', factionIds: [], reactive: false, formation: 'line', randomness: 0.4, maxUnits: 100 },
  { id: 'kho', name: 'Khó', description: 'Xem quân của bạn rồi chọn quân khắc chế.', difficulty: 4, budgetMultiplier: 1.15, strategy: 'counter', factionIds: [], reactive: true, formation: 'wedge', randomness: 0.2, maxUnits: 120 },
  { id: 'huyen-thoai', name: 'Huyền thoại', description: 'Quân tinh nhuệ, nhiều tiền hơn hẳn.', difficulty: 5, budgetMultiplier: 1.5, strategy: 'elite', factionIds: [], reactive: true, formation: 'flanks', randomness: 0.1, maxUnits: 120 },
];

const settings: Settings = {
  maxUnitsPerSide: 150,
  battleTimeLimit: 300,
  ragdollLimit: 80,
  corpseLimit: 800,
  gravity: 9.8,
  waterSlow: 0.55,
  friendlyFire: true,
  cameraShake: true,
  deathParticleId: 'death-poof',
  splashParticleId: 'splash',
  landParticleId: 'land-dust',
  burnParticleId: 'burn',
  damageMatrix: {
    blunt: { unarmored: 1, light: 1, heavy: 1.1, beast: 0.8, siege: 1.2 },
    slash: { unarmored: 1.2, light: 1, heavy: 0.6, beast: 0.9, siege: 0.5 },
    pierce: { unarmored: 1.1, light: 0.9, heavy: 0.5, beast: 1, siege: 0.4 },
    fire: { unarmored: 1.2, light: 1.1, heavy: 0.9, beast: 1, siege: 1.5 },
    magic: { unarmored: 1, light: 1, heavy: 1, beast: 1.2, siege: 1 },
  },
  economy: {
    boxHours: 3,
    starBonus: 0.1,
    dailyBox: { chest: 'golden', coins: [2, 5], cards: 40, kinds: 3 },
    hourlyBox: { chest: 'silver', coins: [1, 2], cards: 12, kinds: 2 },
    botBoxes: {
      '1': { chest: 'wooden', coins: [1, 3], cards: 8, kinds: 2 },
      '2': { chest: 'silver', coins: [2, 5], cards: 14, kinds: 2 },
      '3': { chest: 'golden', coins: [3, 8], cards: 20, kinds: 3 },
      '4': { chest: 'giant', coins: [5, 12], cards: 28, kinds: 3 },
      '5': { chest: 'magical', coins: [8, 20], cards: 40, kinds: 4 },
    },
    botWinBonusPerExtra: 0.5,
    botWinCooldown: 20,
    botWinMinSeconds: 15,
    botWinDailyCap: 30,
    levelXp: 100,
    levelXpGrowth: 50,
    maxLevel: 50,
    levelBudget: 3000,
    levelBudgetStep: 250,
    xpBotWin: 30,
    xpPvpWin: 50,
    xpPvpLoss: 15,
    xpPvpDraw: 25,
    xpMinSeconds: 30,
  },
  siege: {
    defenseBudget: 1,
    attackBudget: 1,
    tierHeight: 2,
    maxTiers: 3,
    maxWallBlocks: 400,
    towerRangeBonus: 0.3,
    towerCapacity: 2,
    fallDamage: 15,
    rubbleSlow: 0.55,
    climbSpeed: 1.4,
    safeFall: 2.5,
    dashRangedPriority: 60,
    dashWallPriority: 120,
    botWallShare: 0.35,
    botTowerShare: 0.28,
    botCastleHalf: 6,
  },
  ranked: rankedSchema.parse({}),
};

export const SEED: ContentBundle = { factions, units, weapons, projectiles, particles, assets, maps, bots, settings };
